packages:
  - 'packages/**'

catalog:
  '@changesets/cli': 2.29.7
  '@floating-ui/dom': 1.7.5
  '@microsoft/api-extractor': 7.58.9
  '@swc/core': 1.13.5
  '@tailwindcss/typography': 0.5.19
  '@types/dom-navigation': 1.0.6
  '@types/markdown-it': 14.1.2
  '@types/node': 24.9.0
  '@types/web': 0.0.281
  '@vitest/coverage-v8': 4.1.10
  ajv: 8.13.0
  autoprefixer: 10.4.24
  consola: 3.4.2
  custom-elements-manifest: 2.1.0
  esbuild: 0.28.1
  fast-glob: 3.3.3
  happy-dom: 20.10.6
  highlight.js: 11.11.1
  jiti: 2.6.1
  markdown-it: 14.3.0
  markdown-it-anchor: 9.2.0
  markdown-it-highlightjs: 4.3.0
  markdown-it-toc-done-right: 4.2.0
  postcss: 8.5.10
  reflect-metadata: 0.2.2
  tailwindcss: 3.4.19
  typescript: 6.0.3
  vite: 8.2.0
  vite-plugin-dts: 5.0.3
  vitest: 4.1.10

catalogs:
  peer-reflect-metadata:
    reflect-metadata: '>=0.2.0'
  peer-vite:
    vite: ^8.1.0

allowBuilds:
  '@swc/core': true
  esbuild: true
