import {BaseElement, Component, HTML} from "@ayu-sh-kr/dota-core";


@Component({
    selector: 'app-feature',
    shadow: false
})
export class FeatureComponent extends BaseElement {

    items: FeatureInfo[] = [
        {
            icon: 'material-symbols:blur-circular-outline',
            title: 'Minimal API',
            description: 'No runtime overhead — compiles directly to native Custom Elements.'
        },

        {
            icon: 'material-symbols:performance-max-outline-rounded',
            title: 'Decorator-Driven',
            description: 'Decorator API keeps component code readable with minimal ceremony.'
        },

        {
            icon: 'material-symbols:extension-rounded',
            title: 'Framework-Agnostic',
            description: 'One codebase; works in React, Vue, Angular, or plain HTML.'
        },

        {
            icon: 'material-symbols:deployed-code',
            title: 'Standards-Based',
            description: 'Built on Web Component standards — no proprietary abstractions, no lock-in.'
        }
    ]

    constructor() {
        super();
    }


    render(): string {
        return HTML`
        <!-- LOCKED CONTENT: Do not modify text; content generated by Prompt A -->
        <section role="region" aria-labelledby="feature-heading"
                 class="font-dm mx-auto max-w-7xl px-6 pt-4 pb-20">

            <!-- Section header -->
            <div class="hero-fade-up flex flex-col items-center text-center gap-3 mb-12">
                <span class="text-xs font-bold tracking-[0.2em] uppercase text-purple-400 dark:text-purple-300">
                    Why Dota
                </span>
                <h2 id="feature-heading"
                    class="text-3xl sm:text-4xl font-bold text-gray-800 dark:text-gray-100/90 leading-tight tracking-tight max-w-2xl">
                    Ship reusable UI components that work natively in any stack.
                </h2>
            </div>

            <!-- LOCKED CONTENT: Do not modify text; content generated by Prompt A -->
            <div data-locked="true"
                 class="hero-fade-up hero-delay-1 grid lg:grid-cols-4 sm:grid-cols-2 grid-cols-1 gap-4">
                ${this.items.map((item, i) => {
                    return `<div class="group flex flex-col gap-5 p-6 rounded-2xl
                                        border border-gray-200/60 dark:border-gray-700/40
                                        bg-white/50 dark:bg-gray-900/40
                                        hover:-translate-y-1 hover:shadow-lg hover:border-purple-500/30
                                        transition-all duration-200 cursor-default"
                                 tabindex="0"
                                 style="animation-delay:${i * 60}ms">
                                <span class="text-purple-400 dark:text-purple-300">
                                    <dota-icon name="${item.icon}" color="purple" size="lg" variant="ghost"></dota-icon>
                                </span>
                                <div class="flex flex-col gap-2">
                                    <h3 class="text-sm font-semibold text-gray-700 dark:text-gray-300 tracking-wide">
                                        ${item.title}
                                    </h3>
                                    <p class="text-sm text-gray-400 dark:text-gray-500 leading-relaxed">
                                        ${item.description}
                                    </p>
                                </div>
                            </div>`
                }).join('')}
            </div>

            <!-- CTA -->
            <div class="hero-fade-up hero-delay-2 flex justify-center mt-10">
                <a href="/docs?content=Getting-Started.md"
                   class="hero-cta-secondary text-sm font-medium text-gray-400 dark:text-gray-500
                          hover:text-purple-400 dark:hover:text-purple-400
                          transition-colors duration-200 flex items-center gap-1.5"
                   aria-label="Explore the Dota API documentation">
                    Explore the API
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </div>

        </section>
        `;
    }

}

export interface FeatureInfo {
    icon: string
    title: string,
    description: string
}