import markdownit from 'markdown-it';
import highlightjs from 'markdown-it-highlightjs';
import 'highlight.js/styles/github-dark.css';
import anchor from "markdown-it-anchor"
import toc from "markdown-it-toc-done-right"

export interface TocEntry {
  /** Heading level (1–6) */
  level: number;
  /** Heading text */
  text: string;
  /** The anchor id generated by markdown-it-anchor */
  id: string;
  children: TocEntry[];
}

/** Flatten the AST produced by markdown-it-toc-done-right into a simple list */
function flattenTocAst(node: { l: number; n: string; c: typeof node[] }): TocEntry[] {
  const entries: TocEntry[] = [];
  for (const child of (node.c ?? [])) {
    const id = child.n
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w-]/g, '');
    const entry: TocEntry = { level: child.l, text: child.n, id, children: [] };
    entry.children = flattenTocAst(child);
    entries.push(entry);
  }
  return entries;
}

export interface MarkdownResult {
  html: string;
  toc: TocEntry[];
}

let _lastToc: TocEntry[] = [];

/** Single shared instance — creating markdownit + plugins is not cheap */
const md = markdownit({
  html: true,
  linkify: true,
  typographer: true,
  breaks: false,
}).use(highlightjs, { auto: true, code: true })
  .use(anchor)
  .use(toc, {
    callback(_html: string, ast: { l: number; n: string; c: any[] }) {
      _lastToc = flattenTocAst(ast);
    }
  });

export class MarkdownService {
  static renderMarkdown(content: string): string {
    return md.render(content);
  }

  /**
   * Render markdown and also return the extracted TOC entries.
   * No [[toc]] placeholder is needed in the source markdown.
   */
  static renderMarkdownWithToc(content: string): MarkdownResult {
    _lastToc = [];
    // Prepend [[toc]] to trigger the plugin callback, then strip the nav block
    const html = md.render(`[[toc]]\n${content}`);
    const cleaned = html.replace(/<nav class="table-of-contents">[\s\S]*?<\/nav>\n?/, '');
    return { html: cleaned, toc: _lastToc };
  }
}