import markdownit, { type Options as MarkdownItOptions } from 'markdown-it';
import highlightjs from 'markdown-it-highlightjs';
import anchor from 'markdown-it-anchor';
import toc from 'markdown-it-toc-done-right';
import { ApplicationEventService } from '@ayu-sh-kr/dota-core';
import MarkdownIt from "markdown-it";


/** A single entry in the extracted Table of Contents. */
export interface TocEntry {
  /** Heading level (1–6). */
  level: number;
  /** Heading text as it appears in the source. */
  text: string;
  /** Anchor id generated by markdown-it-anchor. */
  id: string;
  /** Nested child headings. */
  children: TocEntry[];
}

/**
 * Combined result returned by the render methods.
 * Both fields are always present; consumers can ignore whichever they don't need.
 */
export interface MarkdownResult {
  /** Fully rendered HTML string, ready to set as `innerHTML`. */
  html: string;
  /** Flat/nested TOC entries extracted from the document. */
  toc: TocEntry[];
}

/** Recursively flatten the AST produced by markdown-it-toc-done-right. */
function flattenTocAst(node: { l: number; n: string; c: typeof node[] }): TocEntry[] {
  return (node.c ?? []).map(child => {
    const id = child.n
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w-]/g, '');
    return {
      level: child.l,
      text: child.n,
      id,
      children: flattenTocAst(child),
    };
  });
}

/** Build a fresh markdown-it instance wired up with the standard plugin set. */
function buildMd(options: MarkdownItOptions = {}): ReturnType<typeof markdownit> {
  return markdownit({
    html: true,
    linkify: true,
    typographer: true,
    breaks: false,
    ...options,
  })
    .use(highlightjs, { auto: true, code: true })
    .use(anchor)
    .use(toc, {
      callback(_html: string, ast: { l: number; n: string; c: any[] }) {
        MDService['_pendingToc'] = flattenTocAst(ast);
      },
    });
}

/**
 * `MDService` — singleton markdown rendering service for `dota-md`.
 *
 * ### Features
 * - **Default static md instance** — pre-configured with highlight.js, anchors,
 *   and TOC; replace it at any time via `MDService.setMd(...)`.
 * - **LRU-style cache** — results are keyed by content string, so repeated renders
 *   of the same document are instantaneous.  Call `MDService.clearCache()` or
 *   `MDService.clearCacheFor(content)` to invalidate.
 * - **Flexible return** — use `renderHtml` for HTML only, `renderToc` for TOC
 *   only, or `render` for both in a single `MarkdownResult`.
 * - **Optional event publishing** — pass `{ publish: true }` and the service
 *   fires a single `'md:render'` event containing the full `MarkdownResult` so
 *   sibling components (e.g. `doc-toc`) can react without polling the DOM.
 *
 * @example
 * ```ts
 * // HTML + TOC, publish to even bus
 * const result = MDService.render(rawMd, { publish: true });
 *
 * // HTML only (no event, cached)
 * const html = MDService.renderHtml(rawMd);
 *
 * // Replace the underlying md instance (e.g., add a custom plugin)
 * MDService.setMd(markdownit().use(myPlugin));
 * ```
 */
export class MDService {

  private static _md: MarkdownIt = buildMd();

  /**
   * Scratch-pad written by the toc plugin callback during each `md.render()`.
   * Declared here so the `buildMd` closure can write into it.
   * @internal
   */
  private static _pendingToc: TocEntry[] = [];

  /**
   * Content → MarkdownResult cache.
   * Using a `Map` preserves insertion order; the key is the raw markdown string.
   */
  private static _cache = new Map<string, MarkdownResult>();

  /** Maximum number of entries kept in the cache before the oldest is evicted. */
  private static _cacheLimit = 50;

  /** Write a result to the cache, evicting the oldest entry when over the limit. */
  private static _cacheSet(key: string, value: MarkdownResult): void {
    if (MDService._cache.size >= MDService._cacheLimit) {
      // Evict the oldest entry (first key in insertion order)
      MDService._cache.delete(MDService._cache.keys().next().value!);
    }
    MDService._cache.set(key, value);
  }

  /**
   * Replace the underlying `markdown-it` instance.
   * The new instance **must** already have the toc plugin attached with a
   * callback that writes into `MDService['_pendingToc']`, otherwise TOC
   * extraction will stop working.  Use the exported `buildMd` factory to
   * construct a compatible instance.
   *
   * Calling this automatically clears the cache so stale HTML is not served.
   *
   * @param md - A pre-configured `markdown-it` instance.
   */
  static setMd(md: ReturnType<typeof markdownit>): void {
    MDService._md = md;
    MDService._cache.clear();
  }

  /**
   * Adjust the maximum number of cached results (default: 50).
   * Setting a smaller value will immediately evict excess entries.
   */
  static setCacheLimit(limit: number): void {
    MDService._cacheLimit = limit;
    while (MDService._cache.size > limit) {
      MDService._cache.delete(MDService._cache.keys().next().value!);
    }
  }

  /** Remove all cached results. */
  static clearCache(): void {
    MDService._cache.clear();
  }

  /** Remove the cached result for one specific content string. */
  static clearCacheFor(content: string): void {
    MDService._cache.delete(content);
  }

  /**
   * Render markdown into HTML and extract TOC entries.
   * Results are cached by content string; pass `{ bust: true }` to force
   * a fresh render even when a cached result exists.
   *
   * @param content  Raw markdown string.
   * @param options
   *   - `publish` — when `true` the result is published to the event bus as
   *                  a single `'md:render'` event so sibling components can react.
   *   - `bust` — when `true` the cache entry for this content is discarded
   *                  before rendering.
   */
  static render(
    content: string,
    options: { publish?: boolean; bust?: boolean } = {},
  ): MarkdownResult {
    const { publish = false, bust = false } = options;

    if (bust) MDService._cache.delete(content);

    const cached = MDService._cache.get(content);
    if (cached) {
      if (publish) MDService._publish(cached);
      return cached;
    }

    // Reset scratch-pad before render so leftover state never leaks
    MDService._pendingToc = [];

    // Prepend [[toc]] to trigger the plugin callback, then strip the nav block
    const raw     = MDService._md.render(`[[toc]]\n${content}`);
    const html    = raw.replace(/<nav class="table-of-contents">[\s\S]*?<\/nav>\n?/, '');
    const result: MarkdownResult = { html, toc: MDService._pendingToc };

    MDService._cacheSet(content, result);

    if (publish) MDService._publish(result);

    return result;
  }

  /**
   * Render markdown and return only the HTML string.
   * The result is still cached, so a follow-up `render()` call is free.
   */
  static renderHtml(content: string, options: { bust?: boolean } = {}): string {
    return MDService.render(content, options).html;
  }

  /**
   * Extract TOC entries without caring about the HTML.
   * The result is still cached, so a follow-up `render()` call is free.
   */
  static renderToc(content: string, options: { bust?: boolean } = {}): TocEntry[] {
    return MDService.render(content, options).toc;
  }


  /** Publish the result as a single `'md:render'` event on the shared bus. */
  private static _publish(result: MarkdownResult): void {
    try {
      ApplicationEventService
        .getInstance()
        .getPublisher()
        .publishAsync({ name: 'md:render', data: result });
    } catch {
      // Guard: if the event bus is not available (e.g., unit-test environment),
      // we silently skip publishing rather than crashing the render.
    }
  }
}