name: Publish packages to NPM
on:
  workflow_run:
    workflows: [ Build ]
    branches: [ master ]
    types: [ completed ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm -r run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish --access public --yes
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
